openapi: 3.0.3
info:
  title: Timecrack API
  version: 1.0.0
  description: These are the OpenAPI specs that describe the REST API of Timecrack.
  termsOfService: https://timecrack.org/terms-and-conditions
  contact:
    name: Timecrack
    url: https://timecrack.org
    email: info@timecrack.org
  license:
    name: GPL-3.0
    url: https://www.gnu.org/licenses/gpl-3.0.en.html
servers:
  - url: http://localhost/api/v1/
tags:
  - name: example
paths:
  /example:
    get:
      tags:
        - example
      summary: Example
      responses:
        '200':
          description: OK
